tasks:
  - name: terraform
    before: |
      source ./bin/install_cli_terraform.sh
      source ./bin/generate_trfc_credentials
      source ./bin/./bin/set_tf_alias

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
      source ./bin/./bin/set_tf_alias
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform

